<?php
declare(strict_types=1); require __DIR__.'/bootstrap.php'; try{$a=$_GET['action']??'health';$p=db();
if($a==='health')ok(['service'=>'royal-online','database'=>'connected']); if($a==='csrf')ok(['csrf'=>csrf()]); if($a==='me')ok(['user'=>me()]);
if($a==='register'){checkcsrf();$d=body();$un=trim($d['username']??'');$em=trim($d['email']??'');$pw=$d['password']??'';if(!preg_match('/^[A-Za-z0-9_]{4,32}$/',$un))fail('Username 4-32 ký tự');if(!filter_var($em,FILTER_VALIDATE_EMAIL))fail('Email không hợp lệ');if(strlen($pw)<8)fail('Mật khẩu tối thiểu 8 ký tự');$p->beginTransaction();try{$s=$p->prepare('INSERT INTO users(username,email,password_hash) VALUES(?,?,?) RETURNING id');$s->execute([$un,$em,password_hash($pw,PASSWORD_DEFAULT)]);$id=(int)$s->fetchColumn();$p->prepare('INSERT INTO wallets(user_id,balance) VALUES(?,1000000)')->execute([$id]);$p->prepare('INSERT INTO wallet_transactions(user_id,type,amount,balance_before,balance_after,description) VALUES(?,?,?,?,?,?)')->execute([$id,'initial',1000000,0,1000000,'Số dư TEST ban đầu']);$p->commit();}catch(Throwable $e){$p->rollBack();if($e instanceof PDOException&&$e->getCode()==='23505')fail('Username hoặc email đã tồn tại',409);throw $e;}session_regenerate_id(true);$_SESSION['user_id']=$id;ok(['user'=>me(),'csrf'=>csrf()],201);}
if($a==='login'){checkcsrf();$d=body();$l=trim($d['login']??'');$pw=$d['password']??'';$s=$p->prepare('SELECT * FROM users WHERE username=? OR email=? LIMIT 1');$s->execute([$l,$l]);$u=$s->fetch();if(!$u||!password_verify($pw,$u['password_hash']))fail('Sai tài khoản hoặc mật khẩu',401);if($u['status']!=='active')fail('Tài khoản đã bị khóa',403);session_regenerate_id(true);$_SESSION['user_id']=(int)$u['id'];$p->prepare('UPDATE users SET last_login_at=now(),updated_at=now() WHERE id=?')->execute([$u['id']]);ok(['user'=>me(),'csrf'=>csrf()]);}
if($a==='logout'){checkcsrf();$_SESSION=[];session_destroy();ok();}
if($a==='wallet'){ $u=user();$s=$p->prepare('SELECT * FROM wallet_transactions WHERE user_id=? ORDER BY id DESC LIMIT 100');$s->execute([$u['id']]);ok(['balance'=>(int)$u['balance'],'transactions'=>$s->fetchAll()]);}
if($a==='games'){ $s=$p->query("SELECT id,code,name,category,status,min_bet,max_bet,round_seconds FROM games WHERE status='active' ORDER BY sort_order,id");ok(['games'=>$s->fetchAll()]);}
if($a==='place_bet'){checkcsrf();$u=user();$d=body();$code=trim($d['game']??'');$sel=trim($d['selection']??'');$amt=(int)($d['amount']??0);$s=$p->prepare("SELECT * FROM games WHERE code=? AND status='active'");$s->execute([$code]);$g=$s->fetch();if(!$g)fail('Game không hoạt động',404);if($amt<(int)$g['min_bet']||$amt>(int)$g['max_bet'])fail('Mức cược ngoài giới hạn',422);if(!$sel)fail('Chưa chọn cửa');$p->beginTransaction();try{$w=$p->prepare('SELECT balance FROM wallets WHERE user_id=? FOR UPDATE');$w->execute([$u['id']]);$before=(int)$w->fetchColumn();if($before<$amt){$p->rollBack();fail('Số dư không đủ',422);}$rn=$code.'-'.date('YmdHis').'-'.bin2hex(random_bytes(3));$r=$p->prepare("INSERT INTO game_rounds(game_id,round_no) VALUES(?,?) RETURNING id");$r->execute([$g['id'],$rn]);$rid=(int)$r->fetchColumn();$p->prepare('UPDATE wallets SET balance=balance-?,updated_at=now() WHERE user_id=?')->execute([$amt,$u['id']]);$b=$p->prepare('INSERT INTO bets(user_id,game_id,round_id,selection,stake) VALUES(?,?,?,?,?) RETURNING id');$b->execute([$u['id'],$g['id'],$rid,$sel,$amt]);$bid=(int)$b->fetchColumn();$p->prepare('INSERT INTO wallet_transactions(user_id,type,amount,balance_before,balance_after,reference_type,reference_id,description) VALUES(?,?,?,?,?,?,?,?)')->execute([$u['id'],'bet',-$amt,$before,$before-$amt,'bet',$bid,'Đặt cược TEST']);$p->commit();ok(['bet_id'=>$bid,'balance'=>$before-$amt]);}catch(Throwable $e){$p->rollBack();throw $e;}}
if($a==='settle_demo'){checkcsrf();$u=user();$d=body();$bid=(int)($d['bet_id']??0);$s=$p->prepare("SELECT b.*,g.code FROM bets b JOIN games g ON g.id=b.game_id WHERE b.id=? AND b.user_id=? AND b.status='accepted'");$s->execute([$bid,$u['id']]);$b=$s->fetch();if(!$b)fail('Ván không hợp lệ',404);$win=random_int(0,1)===1;$pay=$win?(int)$b['stake']*2:0;$p->beginTransaction();try{$w=$p->prepare('SELECT balance FROM wallets WHERE user_id=? FOR UPDATE');$w->execute([$u['id']]);$before=(int)$w->fetchColumn();$after=$before+$pay;$p->prepare('UPDATE bets SET status=?,payout=?,settled_at=now() WHERE id=?')->execute([$win?'won':'lost',$pay,$bid]);$p->prepare("UPDATE game_rounds SET status='settled',result_json=?::jsonb,settled_at=now() WHERE id=?")->execute([json_encode(['demo_win'=>$win,'generated_at'=>date(DATE_ATOM)]),$b['round_id']]);if($pay){$p->prepare('UPDATE wallets SET balance=balance+?,updated_at=now() WHERE user_id=?')->execute([$pay,$u['id']]);$p->prepare('INSERT INTO wallet_transactions(user_id,type,amount,balance_before,balance_after,reference_type,reference_id,description) VALUES(?,?,?,?,?,?,?,?)')->execute([$u['id'],'win',$pay,$before,$after,'bet',$bid,'Thắng TEST']);}$p->commit();ok(['status'=>$win?'won':'lost','payout'=>$pay,'balance'=>$after]);}catch(Throwable $e){$p->rollBack();throw $e;}}
if($a==='faq'){ $items=$p->query('SELECT id,question,answer FROM support_faq WHERE active=true ORDER BY id')->fetchAll(); ok(['items'=>$items]); }
if($a==='support_thread'){ $u=user(); $s=$p->prepare("SELECT * FROM chat_threads WHERE user_id=? ORDER BY updated_at DESC LIMIT 1");$s->execute([$u['id']]);$t=$s->fetch();if(!$t){$p->prepare('INSERT INTO chat_threads(user_id) VALUES(?) RETURNING id')->execute([$u['id']]);$tid=(int)$p->lastInsertId();$t=['id'=>$tid,'user_id'=>$u['id'],'status'=>'open'];}$m=$p->prepare('SELECT cm.id,cm.sender_type,cm.message,cm.created_at,u.username FROM chat_messages cm LEFT JOIN users u ON u.id=cm.sender_user_id WHERE cm.thread_id=? ORDER BY cm.id ASC LIMIT 300');$m->execute([(int)$t['id']]);ok(['thread'=>$t,'messages'=>$m->fetchAll()]); }
if($a==='support_send'){ checkcsrf();$u=user();$d=body();$msg=trim((string)($d['message']??''));if($msg==='')fail('Nội dung trống');$s=$p->prepare("SELECT id FROM chat_threads WHERE user_id=? AND status='open' ORDER BY id DESC LIMIT 1");$s->execute([$u['id']]);$tid=$s->fetchColumn();if(!$tid){$p->prepare('INSERT INTO chat_threads(user_id) VALUES(?) RETURNING id')->execute([$u['id']]);$tid=$p->lastInsertId();}$p->prepare("INSERT INTO chat_messages(thread_id,sender_user_id,sender_type,message) VALUES(?,?, 'user',?)")->execute([$tid,$u['id'],$msg]);$p->prepare('UPDATE chat_threads SET updated_at=now() WHERE id=?')->execute([$tid]);ok(['thread_id'=>(int)$tid]); }
if($a==='deposit_request'||$a==='withdraw_request'){checkcsrf();$u=user();$d=body();$amt=(int)($d['amount']??0);$method=trim((string)($d['method']??''));$info=trim((string)($d['account_info']??''));$note=trim((string)($d['note']??''));if($amt<=0||$amt>1000000000)fail('Số tiền không hợp lệ');if(!$method)fail('Chưa chọn phương thức');if(!$info)fail('Thiếu thông tin giao dịch');$type=$a==='deposit'?'deposit':'withdraw';if($type==='withdraw'){ $w=$p->prepare('SELECT balance FROM wallets WHERE user_id=?');$w->execute([$u['id']]);if((int)$w->fetchColumn()<$amt)fail('Số dư TEST không đủ để tạo yêu cầu rút',422); }$p->prepare('INSERT INTO money_requests(user_id,type,amount,method,account_info,proof_note) VALUES(?,?,?,?,?,?)')->execute([$u['id'],$type,$amt,$method,$info,$note]);ok(); }
if($a==='money_requests'){ $u=user();$s=$p->prepare('SELECT id,type,amount,method,account_info,proof_note,status,admin_note,created_at,processed_at FROM money_requests WHERE user_id=? ORDER BY id DESC LIMIT 100');$s->execute([$u['id']]);ok(['items'=>$s->fetchAll()]); }
if($a==='admin_money_requests'){admin();$st=trim($_GET['status']??'');$sql="SELECT r.*,u.username,u.email,a.username processed_by_name FROM money_requests r JOIN users u ON u.id=r.user_id LEFT JOIN users a ON a.id=r.processed_by";if(in_array($st,['pending','approved','rejected'],true)){$sql.=' WHERE r.status=?';$sql.=' ORDER BY r.id DESC LIMIT 300';$q=$p->prepare($sql);$q->execute([$st]);}else{$sql.=' ORDER BY r.id DESC LIMIT 300';$q=$p->query($sql);}ok(['items'=>$q->fetchAll()]); }
if($a==='admin_process_money'){checkcsrf();$ad=admin();$d=body();$id=(int)($d['id']??0);$status=$d['status']??'';$note=trim((string)($d['note']??''));if(!in_array($status,['approved','rejected'],true))fail('Trạng thái không hợp lệ');$p->beginTransaction();try{$s=$p->prepare('SELECT * FROM money_requests WHERE id=? FOR UPDATE');$s->execute([$id]);$r=$s->fetch();if(!$r||$r['status']!=='pending'){ $p->rollBack();fail('Yêu cầu không còn chờ duyệt',409);}if($status==='approved'){$w=$p->prepare('SELECT balance FROM wallets WHERE user_id=? FOR UPDATE');$w->execute([$r['user_id']]);$before=(int)$w->fetchColumn();$amt=(int)$r['amount'];if($r['type']==='withdraw'){if($before<$amt){$p->rollBack();fail('Số dư TEST không đủ để duyệt rút',422);} $after=$before-$amt;$p->prepare('UPDATE wallets SET balance=?,updated_at=now() WHERE user_id=?')->execute([$after,$r['user_id']]);$p->prepare("INSERT INTO wallet_transactions(user_id,type,amount,balance_before,balance_after,reference_type,reference_id,description) VALUES(?,?,?,?,?,?,?,?)")->execute([$r['user_id'],'withdraw',-$amt,$before,$after,'money_request',$id,'Rút TEST được admin duyệt']);}else{$after=$before+$amt;$p->prepare('UPDATE wallets SET balance=?,updated_at=now() WHERE user_id=?')->execute([$after,$r['user_id']]);$p->prepare("INSERT INTO wallet_transactions(user_id,type,amount,balance_before,balance_after,reference_type,reference_id,description) VALUES(?,?,?,?,?,?,?,?)")->execute([$r['user_id'],'deposit',$amt,$before,$after,'money_request',$id,'Nạp TEST được admin duyệt']);}}$p->prepare('UPDATE money_requests SET status=?,admin_note=?,processed_at=now(),processed_by=? WHERE id=?')->execute([$status,$note,$ad['id'],$id]);audit((int)$ad['id'],'money_request_'.$status,(int)$r['user_id'],['request_id'=>$id,'type'=>$r['type'],'amount'=>(int)$r['amount'],'note'=>$note]);$p->commit();ok();}catch(Throwable $e){if($p->inTransaction())$p->rollBack();throw $e;}}
if($a==='admin_chat_threads'){admin();$s=$p->query("SELECT t.id,t.user_id,t.status,t.created_at,t.updated_at,u.username,u.email,(SELECT message FROM chat_messages m WHERE m.thread_id=t.id ORDER BY m.id DESC LIMIT 1) last_message FROM chat_threads t JOIN users u ON u.id=t.user_id ORDER BY t.updated_at DESC LIMIT 300");ok(['items'=>$s->fetchAll()]);}
if($a==='admin_chat_messages'){admin();$id=(int)($_GET['thread_id']??0);$s=$p->prepare("SELECT m.id,m.sender_type,m.message,m.created_at,u.username FROM chat_messages m LEFT JOIN users u ON u.id=m.sender_user_id WHERE m.thread_id=? ORDER BY m.id ASC LIMIT 500");$s->execute([$id]);ok(['items'=>$s->fetchAll()]);}
if($a==='admin_chat_send'){checkcsrf();$ad=admin();$d=body();$tid=(int)($d['thread_id']??0);$msg=trim((string)($d['message']??''));if(!$tid||!$msg)fail('Thiếu dữ liệu');$p->prepare("INSERT INTO chat_messages(thread_id,sender_user_id,sender_type,message) VALUES(?,?, 'admin',?)")->execute([$tid,$ad['id'],$msg]);$p->prepare('UPDATE chat_threads SET updated_at=now(),status=\'open\' WHERE id=?')->execute([$tid]);audit((int)$ad['id'],'support_reply',null,['thread_id'=>$tid]);ok();}
if($a==='admin_close_thread'){checkcsrf();$ad=admin();$d=body();$id=(int)($d['thread_id']??0);$p->prepare("UPDATE chat_threads SET status='closed',updated_at=now() WHERE id=?")->execute([$id]);audit((int)$ad['id'],'support_thread_close',null,['thread_id'=>$id]);ok();}
if($a==='history'){$u=user();$s=$p->prepare('SELECT b.id,g.name game,b.selection,b.stake,b.payout,b.status,b.created_at,b.settled_at FROM bets b JOIN games g ON g.id=b.game_id WHERE b.user_id=? ORDER BY b.id DESC LIMIT 100');$s->execute([$u['id']]);ok(['items'=>$s->fetchAll()]);}
if($a==='lobby_messages'){ require_login(); $s=$pdo->query("SELECT id,sender_name,message,is_bot,created_at FROM lobby_messages ORDER BY id DESC LIMIT 80"); $rows=array_reverse($s->fetchAll()); json_out(['items'=>$rows]); }
if($a==='lobby_send' && $_SERVER['REQUEST_METHOD']==='POST'){ $u=require_login(); $b=body(); $msg=trim((string)($b['message']??'')); if($msg==='') json_out(['error'=>'Tin nhắn trống'],422); $msg=mb_substr($msg,0,300); $pdo->prepare("INSERT INTO lobby_messages(user_id,sender_name,message,is_bot) VALUES(?,?,?,FALSE)")->execute([$u['id'],$u['username'],$msg]); $q=mb_strtolower($msg); $replies=['Bot Luna'=>'Chào bạn 👋 Chúc bạn chơi vui!','Bot Ken'=>'Mọi người đang ở sảnh HA88Lucky đó!','Bot Miu'=>'Bạn đang chơi game nào vậy?','Bot Tom'=>'Nhớ kiểm tra thông tin cược trước khi bắt đầu nhé.']; $reply=null; if(str_contains($q,'chào')||str_contains($q,'hello'))$reply='Chào bạn 👋 Mình là bot hỗ trợ sảnh HA88Lucky.'; elseif(str_contains($q,'game'))$reply='Sảnh hiện có nhiều game. Bạn có thể chọn game ở bên trên.'; elseif(str_contains($q,'admin')||str_contains($q,'hỗ trợ'))$reply='Nếu cần hỗ trợ riêng, hãy dùng Chat hỗ trợ để nhắn với admin.'; elseif(str_contains($q,'nạp')||str_contains($q,'rút'))$reply='Nạp/rút TEST được gửi thành yêu cầu và admin quản lý.'; if($reply){$bot=array_rand($replies);$pdo->prepare("INSERT INTO lobby_messages(user_id,sender_name,message,is_bot) VALUES(NULL,?,?,TRUE)")->execute([$bot,$reply]);} json_out(['ok'=>true]); }
if($a==='admin_game_audio' && $_SERVER['REQUEST_METHOD']==='POST'){ $ad=require_admin(); $b=body(); $code=trim((string)($b['game_code']??'')); $mu=trim((string)($b['music_url']??'')); $eu=trim((string)($b['effect_url']??'')); $vol=max(0,min(1,(float)($b['volume']??.7))); $pdo->prepare("INSERT INTO game_audio_settings(game_code,music_url,effect_url,volume) VALUES(?,?,?,?) ON CONFLICT(game_code) DO UPDATE SET music_url=EXCLUDED.music_url,effect_url=EXCLUDED.effect_url,volume=EXCLUDED.volume,updated_at=NOW()")->execute([$code,$mu,$eu,$vol]); audit($ad['id'],'update_game_audio',null,['game_code'=>$code]); json_out(['ok'=>true]); }
if($a==='game_audio'){ $code=trim((string)($_GET['game_code']??'')); $s=$pdo->prepare('SELECT * FROM game_audio_settings WHERE game_code=?');$s->execute([$code]);json_out(['settings'=>$s->fetch()]); }
if($a==='admin_overview'){admin();ok(['users'=>(int)$p->query("SELECT count(*) FROM users WHERE role='user'")->fetchColumn(),'active_users'=>(int)$p->query("SELECT count(*) FROM users WHERE role='user' AND status='active'")->fetchColumn(),'total_balance'=>(int)$p->query('SELECT COALESCE(sum(balance),0) FROM wallets')->fetchColumn(),'active_games'=>(int)$p->query("SELECT count(*) FROM games WHERE status='active'")->fetchColumn()]);}
if($a==='admin_users'){admin();$q=trim($_GET['q']??'');$s=$p->prepare('SELECT u.id,u.username,u.email,u.role,u.status,u.created_at,u.last_login_at,w.balance FROM users u JOIN wallets w ON w.user_id=u.id WHERE u.role=\'user\' AND (u.username ILIKE ? OR u.email ILIKE ?) ORDER BY u.id DESC LIMIT 200');$like="%$q%";$s->execute([$like,$like]);ok(['items'=>$s->fetchAll()]);}
if($a==='admin_set_status'){checkcsrf();$ad=admin();$d=body();$id=(int)($d['user_id']??0);$st=$d['status']??'';if(!in_array($st,['active','blocked'],true))fail('Trạng thái không hợp lệ');$p->prepare("UPDATE users SET status=?,updated_at=now() WHERE id=? AND role='user'")->execute([$st,$id]);audit((int)$ad['id'],'user_status_change',$id,['status'=>$st]);ok();}
if($a==='admin_adjust_balance'){checkcsrf();$ad=admin();$d=body();$id=(int)($d['user_id']??0);$amt=(int)($d['amount']??0);$reason=trim($d['reason']??'');if(!$id||!$amt||!$reason)fail('Thiếu dữ liệu');$p->beginTransaction();try{$s=$p->prepare("SELECT w.balance FROM wallets w JOIN users u ON u.id=w.user_id WHERE w.user_id=? AND u.role='user' FOR UPDATE");$s->execute([$id]);$before=$s->fetchColumn();if($before===false){$p->rollBack();fail('Không tìm thấy người chơi',404);}$after=(int)$before+$amt;if($after<0){$p->rollBack();fail('Số dư không thể âm',422);}$p->prepare('UPDATE wallets SET balance=?,updated_at=now() WHERE user_id=?')->execute([$after,$id]);$p->prepare('INSERT INTO wallet_transactions(user_id,type,amount,balance_before,balance_after,description) VALUES(?,?,?,?,?,?)')->execute([$id,'adjustment',$amt,$before,$after,'Admin: '.$reason]);audit((int)$ad['id'],'wallet_adjustment',$id,['amount'=>$amt,'before'=>(int)$before,'after'=>$after,'reason'=>$reason]);$p->commit();ok(['balance'=>$after]);}catch(Throwable $e){$p->rollBack();throw $e;}}
if($a==='admin_games'){admin();ok(['items'=>$p->query('SELECT * FROM games ORDER BY sort_order,id')->fetchAll()]);}
if($a==='admin_update_game'){checkcsrf();$ad=admin();$d=body();$id=(int)($d['id']??0);$st=$d['status']??'';$min=(int)($d['min_bet']??0);$max=(int)($d['max_bet']??0);$sec=(int)($d['round_seconds']??0);if(!in_array($st,['active','maintenance','disabled'],true)||$min<1||$max<$min||$sec<5||$sec>3600)fail('Thông số game không hợp lệ');$p->prepare('UPDATE games SET status=?,min_bet=?,max_bet=?,round_seconds=? WHERE id=?')->execute([$st,$min,$max,$sec,$id]);audit((int)$ad['id'],'game_config_update',null,['game_id'=>$id,'status'=>$st,'min_bet'=>$min,'max_bet'=>$max,'round_seconds'=>$sec]);ok();}
if($a==='admin_audit'){admin();ok(['items'=>$p->query('SELECT a.*,u.username actor FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_user_id ORDER BY a.id DESC LIMIT 300')->fetchAll()]);}
fail('Action không tồn tại',404);
}catch(Throwable $e){error_log((string)$e);fail('Server error',500);}
